apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-demo-deployment
spec:
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: instance
  minReplicas: 1
  maxReplicas: 4096
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Object
    object:
      describedObject:
        kind: Service
        name: instance
      metric:
        name: "autoscaling.googleapis.com|gclb-capacity-utilization"
      target:
        averageValue: 50
        type: AverageValue
