apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance
spec:
  selector:
    matchLabels:
      app: instance
  template:
    metadata:
      labels:
        app: instance
    spec:
      serviceAccountName: gcp
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      
      containers:
      - name: instance
        image: us-central1-docker.pkg.dev/mofilabs-next-demo-02/scaling/instance:v0.1.11
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          periodSeconds: 3
        env:
        - name: PROJECT_ID
          value: "mofilabs-next-demo-02"
        - name: FIRESTORE_COLLECTION
          value: "gke"
        - name: INSTANCE_COLLECTION
          value: "gke-instances"
